spring.application.name=expense-tracker

# ===============================
# DATABASE CONFIGURATION (PostgreSQL Neon / Env configuration)
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-rapid-tooth-aiyniyxv.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_gYQHzpNfer28}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Initial Schema file
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Server Port (dynamic for cloud environments like Render)
server.port=${PORT:8080}
